name: 'Verify "safe to test" label'
description: 'Secret protection for the pull_request_target, achieved by verifying whether the PR from a fork has the "safe to test" label.'
inputs:
  label:
    description: 'The name of the label required to pass the check'
    required: false
    default: 'safe to test'
runs:
  using: 'node24'
  main: 'index.js'
branding:
  icon: shield
  color: white